default: &default
  adapter: postgresql
  encoding: utf8
  pool: 10
  port: 5432
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: wwff_development
  username: postgres
  password: 

production:
  <<: *default
  host: <%= Figaro.env.database_host %>
  database: <%= Figaro.env.database_name %>
  username: <%= Figaro.env.database_username %>
  password: <%= Figaro.env.database_password %>

